# Generated by Django 5.0.1 on 2024-08-07 09:07

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_booking_coupons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='success_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnopqrstuvwxyz', blank=True, length=10, max_length=20, null=True, prefix='', unique=True),
        ),
    ]
